# Generated by Django 4.1.5 on 2023-02-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entregable',
            new_name='Entregables',
        ),
        migrations.RenameField(
            model_name='entregables',
            old_name='fechaDeEntrega',
            new_name='fecha',
        ),
    ]
